# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [3]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [8]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.4


In [9]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [10]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [29]:

vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [21]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [22]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [23]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [24]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [25]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [26]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.03986214 0.78536913 0.04060586 0.30427473 0.3953139 ]
 [0.07720429 0.83351404 0.37449266 0.5082937  0.43164359]
 [0.27394806 0.55152146 0.98731451 0.31093227 0.4399405 ]
 [0.15617424 0.19089824 0.47541759 0.50883057 0.13367666]
 [0.74775219 0.38912953 0.23995139 0.69330722 0.50679167]]

[[ 0.5307325  -1.32580392  1.18409043 -1.01864297 -0.21212618]
 [ 0.03844286 -2.74267946  0.11628978 -0.76969698  0.29087144]
 [ 0.45132281  0.56227369  0.32365992  2.46354191  1.94726982]
 [-1.14127984  0.54675836 -0.58152181  0.16589233  0.6191329 ]
 [ 1.96824734 -2.76705095  0.12312335  1.06865662  0.4009953 ]
 [-0.05204943  1.6525689   0.3504117   0.30332462  0.13646501]
 [-1.88399358 -0.18079249  0.03218846  0.03737624 -0.80100376]
 [ 0.75444322  1.20723621 -1.89817865 -0.25448973 -0.11266655]
 [ 1.28422513  1.72160555 -0.92786538 -0.79892303  0.31388143]
 [-0.39773167  0.05782375 -0.22746818  1.30750769  0.15422508]]


In [30]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.415846405533653
1.087728182240726


In [31]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.0398621437240666
2.463541912341053


In [ ]:
# break here for next video!

In [32]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[ 0.2245118  -1.31836953 -0.24688632  0.65561375  1.4652666  -0.52831597
  0.31589994  0.89299576 -0.18700634  1.85138584 -1.21630443 -0.12737677
 -0.08624202  2.07052703  0.5369854   1.83730916  1.20127397 -0.60181053
 -1.6952653 ]
0.31589993771582153


In [33]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[ 1.4652666  -0.52831597  0.31589994  0.89299576 -0.18700634]


In [34]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[ 0.2245118   0.65561375  0.31589994  1.85138584 -0.08624202]


In [35]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


[[0.03986214 0.78536913 0.04060586 0.30427473 0.3953139 ]
 [0.07720429 0.83351404 0.37449266 0.5082937  0.43164359]
 [0.27394806 0.55152146 0.98731451 0.31093227 0.4399405 ]
 [0.15617424 0.19089824 0.47541759 0.50883057 0.13367666]
 [0.74775219 0.38912953 0.23995139 0.69330722 0.50679167]]
0.3744926599350442
0.3744926599350442


In [36]:
print(rand_mat[0:2,1:3])

[[0.78536913 0.04060586]
 [0.83351404 0.37449266]]


In [37]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[ 0.2245118  -1.31836953 -0.24688632  0.65561375  1.4652666  -0.52831597
  0.31589994  0.89299576 -0.18700634  1.85138584 -1.21630443 -0.12737677
 -0.08624202  2.07052703  0.5369854   1.83730916  1.20127397 -0.60181053
 -1.6952653 ]

[ 0.2245118  -1.31836953 -0.24688632  4.          4.         -0.52831597
  0.31589994  0.89299576 -0.18700634  1.85138584 -1.21630443 -0.12737677
 -0.08624202  2.07052703  0.5369854   1.83730916  1.20127397 -0.60181053
 -1.6952653 ]

[ 0.2245118  -1.31836953 -0.24688632  1.          2.         -0.52831597
  0.31589994  0.89299576 -0.18700634  1.85138584 -1.21630443 -0.12737677
 -0.08624202  2.07052703  0.5369854   1.83730916  1.20127397 -0.60181053
 -1.6952653 ]


In [38]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.03986214 0.78536913 0.04060586 0.30427473 0.3953139 ]
 [0.07720429 0.83351404 0.37449266 0.5082937  0.43164359]
 [0.27394806 0.55152146 0.98731451 0.31093227 0.4399405 ]
 [0.15617424 0.19089824 0.47541759 0.50883057 0.13367666]
 [0.74775219 0.38912953 0.23995139 0.69330722 0.50679167]]

[[0.03986214 0.78536913 0.04060586 0.30427473 0.3953139 ]
 [0.07720429 0.83351404 0.37449266 0.         0.        ]
 [0.27394806 0.55152146 0.98731451 0.         0.        ]
 [0.15617424 0.19089824 0.47541759 0.50883057 0.13367666]
 [0.74775219 0.38912953 0.23995139 0.69330722 0.50679167]]


In [39]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.03986214 0.78536913 0.04060586]
 [0.07720429 0.83351404 0.37449266]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [40]:
print(rand_mat)

[[3.         3.         3.         0.30427473 0.3953139 ]
 [3.         3.         3.         0.         0.        ]
 [0.27394806 0.55152146 0.98731451 0.         0.        ]
 [0.15617424 0.19089824 0.47541759 0.50883057 0.13367666]
 [0.74775219 0.38912953 0.23995139 0.69330722 0.50679167]]


In [41]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.30427473 0.3953139 ]
 [3.         3.         3.         0.         0.        ]
 [0.27394806 0.55152146 0.98731451 0.         0.        ]
 [0.15617424 0.19089824 0.47541759 0.50883057 0.13367666]
 [0.74775219 0.38912953 0.23995139 0.69330722 0.50679167]]


In [ ]:
# break here for next video

In [42]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[ 0.65450363  0.62052026 -0.88615127  0.6214632  -0.49626319  0.74756682
  1.07946497  1.29580559  2.33570084 -0.36971052 -0.20395239  1.0085829
 -0.5540561  -2.05331257 -0.40280856]
[ True  True False  True False  True  True  True  True False False  True
 False False False]
[0.65450363 0.62052026 0.6214632  0.74756682 1.07946497 1.29580559
 2.33570084 1.0085829 ]


In [43]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[ 0.5307325  -1.32580392  1.18409043 -1.01864297 -0.21212618]
 [ 0.03844286 -2.74267946  0.11628978 -0.76969698  0.29087144]
 [ 0.45132281  0.56227369  0.32365992  2.46354191  1.94726982]
 [-1.14127984  0.54675836 -0.58152181  0.16589233  0.6191329 ]
 [ 1.96824734 -2.76705095  0.12312335  1.06865662  0.4009953 ]
 [-0.05204943  1.6525689   0.3504117   0.30332462  0.13646501]
 [-1.88399358 -0.18079249  0.03218846  0.03737624 -0.80100376]
 [ 0.75444322  1.20723621 -1.89817865 -0.25448973 -0.11266655]
 [ 1.28422513  1.72160555 -0.92786538 -0.79892303  0.31388143]
 [-0.39773167  0.05782375 -0.22746818  1.30750769  0.15422508]]
[0.5307325  1.18409043 0.03844286 0.11628978 0.29087144 0.45132281
 0.56227369 0.32365992 2.46354191 1.94726982 0.54675836 0.16589233
 0.6191329  1.96824734 0.12312335 1.06865662 0.4009953  1.6525689
 0.3504117  0.30332462 0.13646501 0.03218846 0.03737624 0.75444322
 1.20723621 1.28422513 1.72160555 0.31388143 0.05782375 1.30750769
 0.15422508]


In [ ]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

In [44]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [45]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [46]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[ 0.5307325  -1.32580392  1.18409043 -1.01864297 -0.21212618]
 [ 0.03844286 -2.74267946  0.11628978 -0.76969698  0.29087144]
 [ 0.45132281  0.56227369  0.32365992  2.46354191  1.94726982]
 [-1.14127984  0.54675836 -0.58152181  0.16589233  0.6191329 ]
 [ 1.96824734 -2.76705095  0.12312335  1.06865662  0.4009953 ]
 [-0.05204943  1.6525689   0.3504117   0.30332462  0.13646501]
 [-1.88399358 -0.18079249  0.03218846  0.03737624 -0.80100376]
 [ 0.75444322  1.20723621 -1.89817865 -0.25448973 -0.11266655]
 [ 1.28422513  1.72160555 -0.92786538 -0.79892303  0.31388143]
 [-0.39773167  0.05782375 -0.22746818  1.30750769  0.15422508]]



In [ ]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

In [ ]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)